apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-react
  template:
    metadata:
      labels:
        app: frontend-react
    spec:
      containers:
        - name: frontend-react
          image: /frontend-react:latest
          ports:
            - containerPort: 80
